
name: Validate Bicep

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bicep
        run: az bicep install
      - name: Validate
        run: az bicep build --file deploy/main.bicep
